The 100-matrix_mul module
======================

Using matrix_mul
-------------------

SETUP:
	>>> matrix_mul = __import__('100-matrix_mul').matrix_mul

	Test Cases::

	>>> matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
	[[7, 10], [15, 22]]

	>>> mat_a = [[3, 1, 3], [2, 5, 9], [9, 1, 0]]
	>>> mat_b = [[7, -1, 2], [2, -1, -9], [-3, -3, 0]]
        >>> matrix_mul(mat_a, mat_b)
	[[14, -13, -3], [-3, -34, -41], [65, -10, 9]]

	>>> matrix_mul([[1, 2, 3]], [[7], [2], [1]])
	[[14]]

	>>> matrix_mul([[8, 12, 3]], None)
	Traceback (most recent call last):
		Random shii        	      ...
	TypeError: m_b must be a list

	>>> matrix_mul((3, 4, 0), [[9.2], [2.2], [4.7]])
	Traceback (most recent call last):
		        	      ...
        TypeError: m_a must be a list

Passing a matrix with an empty list

    >>> matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
    Traceback (most recent call last):
    	      ...
    ValueError: m_a can't be empty

Passing a matrix which its rows have different size

    >>> matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
    Traceback (most recent call last):
    	      ...
    TypeError: each row of m_b must be of the same size

Passing two matrix that can't be multiplied

    >>> matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
    Traceback (most recent call last):
    	      ...
    ValueError: m_a and m_b can't be multiplied

Missing one argument

    >>> matrix_mul([[1, 2]])
    Traceback (most recent call last):
    	      ...
    TypeError: matrix_mul() missing 1 required positional argument: 'm_b'

Missing arguments

    >>> matrix_mul()
    Traceback (most recent call last):
    	      ...
    TypeError: matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
